cache:
    paths:
        - /root/.m2/repository

stages:
    - build
    - deploy

build:
    stage: build
    image: maven:3.3.9-jdk-8
    script:
        - mvn clean package
    tags:
        - docker

#deploy_staging:
#    stage: deploy
#    image: ruby:2.4
#    script:
#        - apt-get update -qy
#        - apt-get install ruby-dev -y
#        - gem install dpl
#        - dpl --provider=heroku --app=whisper-demo-yyy --api-key=$HEROKU_API_KEY
#    environment:
#        name: prod
#        url: https://whisper-demo-yyy.herokuapp.com
#    only:
#        - master
#    tags:
#        - docker
