version: '2'
services:
    whisper-app:
        image: whisper
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://whisper-postgresql:5432/whisper
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    whisper-postgresql:
        extends:
            file: postgresql.yml
            service: whisper-postgresql
